use std::collections::HashMap;
use std::sync::LazyLock;

#[derive(Debug, Clone)]
pub struct VulnEntry {
    pub id: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub impact: &'static str,
    pub remediation: &'static str,
    pub category: &'static str,
    pub cwe: &'static str,
    pub references: &'static [&'static str],
}

pub static VULN_DB: LazyLock<HashMap<&'static str, VulnEntry>> = LazyLock::new(|| {
    let entries: Vec<VulnEntry> = vec![
        // ── Passive: Header / Response Checks ──
        VulnEntry {
            id: "passive-server-info",
            title: "Server Information Disclosure",
            description: "The Server HTTP header reveals technology and version information, aiding attacker reconnaissance.",
            impact: "Attackers can identify the exact server software and version to find known CVEs.",
            remediation: "Configure the web server to suppress or genericize the Server header.",
            category: "API9:2023 - Improper Inventory Management",
            cwe: "CWE-200",
            references: &["https://cwe.mitre.org/data/definitions/200.html"],
        },
        VulnEntry {
            id: "passive-x-powered-by",
            title: "X-Powered-By Header Disclosure",
            description: "The X-Powered-By header reveals the application framework or language runtime.",
            impact: "Reveals technology stack to attackers for targeted exploitation.",
            remediation: "Remove the X-Powered-By header in your application or web server configuration.",
            category: "API9:2023 - Improper Inventory Management",
            cwe: "CWE-200",
            references: &["https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/08-Fingerprint_Web_Application_Framework"],
        },
        VulnEntry {
            id: "passive-json-api",
            title: "JSON API Endpoint Discovered",
            description: "An endpoint returning application/json was discovered, indicating an API surface.",
            impact: "API endpoints may expose sensitive data or functionality if not properly secured.",
            remediation: "Ensure proper authentication and authorization on all API endpoints.",
            category: "API Discovery",
            cwe: "CWE-200",
            references: &["https://owasp.org/API-Security/editions/2023/en/0xa9-improper-inventory-management/"],
        },
        VulnEntry {
            id: "passive-hsts",
            title: "Missing Strict-Transport-Security (HSTS)",
            description: "The HTTPS site does not set the Strict-Transport-Security header, leaving users vulnerable to SSL stripping.",
            impact: "Man-in-the-middle attackers can downgrade HTTPS connections to HTTP.",
            remediation: "Add Strict-Transport-Security: max-age=31536000; includeSubDomains; preload",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-319",
            references: &["https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html"],
        },
        VulnEntry {
            id: "passive-xcto",
            title: "Missing X-Content-Type-Options",
            description: "The X-Content-Type-Options: nosniff header is absent, allowing MIME-type sniffing.",
            impact: "Browsers may interpret files as a different MIME type, enabling XSS via content sniffing.",
            remediation: "Add X-Content-Type-Options: nosniff to all responses.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-16",
            references: &["https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options"],
        },
        VulnEntry {
            id: "passive-xfo",
            title: "Missing X-Frame-Options",
            description: "The X-Frame-Options header is not set, allowing the page to be embedded in iframes.",
            impact: "The page is vulnerable to clickjacking attacks.",
            remediation: "Add X-Frame-Options: DENY or SAMEORIGIN.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-1021",
            references: &["https://owasp.org/www-community/attacks/Clickjacking"],
        },
        VulnEntry {
            id: "passive-csp-weak",
            title: "Weak Content-Security-Policy",
            description: "The CSP contains unsafe-inline or unsafe-eval, weakening XSS protections.",
            impact: "XSS attacks may succeed despite the presence of a CSP header.",
            remediation: "Remove unsafe-inline and unsafe-eval; use nonces or hashes instead.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-693",
            references: &["https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP"],
        },
        VulnEntry {
            id: "passive-csp-missing",
            title: "Missing Content-Security-Policy",
            description: "No Content-Security-Policy header is set, providing no browser-side XSS mitigation.",
            impact: "No protection against inline script injection or unauthorized resource loading.",
            remediation: "Add a restrictive Content-Security-Policy header.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-693",
            references: &["https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP"],
        },
        VulnEntry {
            id: "passive-cors-creds",
            title: "CORS: Credentials with Wildcard Origin",
            description: "Access-Control-Allow-Origin: * combined with Allow-Credentials: true allows any site to make authenticated requests.",
            impact: "Any website can steal authenticated user data via cross-origin requests.",
            remediation: "Use a specific, validated origin instead of * when credentials are allowed.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-942",
            references: &["https://portswigger.net/web-security/cors"],
        },
        VulnEntry {
            id: "passive-cors-wildcard",
            title: "CORS Wildcard Origin",
            description: "Access-Control-Allow-Origin: * allows any website to read API responses.",
            impact: "Sensitive API data may be accessible from any origin.",
            remediation: "Restrict CORS to specific trusted origins.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-942",
            references: &["https://portswigger.net/web-security/cors"],
        },
        VulnEntry {
            id: "passive-referrer",
            title: "Missing Referrer-Policy",
            description: "No Referrer-Policy header is set; the full URL may leak in Referer headers.",
            impact: "Sensitive URL parameters may be exposed to third-party sites.",
            remediation: "Add Referrer-Policy: strict-origin-when-cross-origin.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-200",
            references: &["https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy"],
        },
        VulnEntry {
            id: "passive-permissions",
            title: "Missing Permissions-Policy",
            description: "Neither Permissions-Policy nor Feature-Policy headers are set.",
            impact: "Browser features (camera, microphone, geolocation) may be used without restriction.",
            remediation: "Add Permissions-Policy to restrict unnecessary browser features.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-16",
            references: &["https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy"],
        },
        VulnEntry {
            id: "passive-cache-json",
            title: "JSON Response Without Cache-Control",
            description: "A JSON API response lacks Cache-Control headers, allowing browser caching of potentially sensitive data.",
            impact: "Sensitive API responses may be stored in browser cache and accessed by other users.",
            remediation: "Add Cache-Control: no-store for sensitive API responses.",
            category: "API10:2023 - Unsafe Consumption of API",
            cwe: "CWE-525",
            references: &["https://cwe.mitre.org/data/definitions/525.html"],
        },
        // ── Passive: New Checks ──
        VulnEntry {
            id: "passive-csrf-missing",
            title: "Missing CSRF Protection",
            description: "HTML forms lack CSRF tokens (csrf, _token, authenticity_token), and cookies use SameSite=None.",
            impact: "Attackers can forge cross-site requests to perform actions on behalf of authenticated users.",
            remediation: "Add CSRF tokens to all state-changing forms; set SameSite=Strict or Lax on cookies.",
            category: "CWE-352 - Cross-Site Request Forgery",
            cwe: "CWE-352",
            references: &["https://owasp.org/www-community/attacks/csrf", "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html"],
        },
        VulnEntry {
            id: "passive-clickjack",
            title: "Clickjacking: No Frame Protection",
            description: "Both X-Frame-Options and CSP frame-ancestors are missing, allowing the page to be framed.",
            impact: "Attackers can overlay invisible iframes to trick users into clicking hidden elements.",
            remediation: "Set X-Frame-Options: DENY and Content-Security-Policy: frame-ancestors 'none'.",
            category: "CWE-1021 - Improper Restriction of Rendered UI Layers",
            cwe: "CWE-1021",
            references: &["https://owasp.org/www-community/attacks/Clickjacking", "https://portswigger.net/web-security/clickjacking"],
        },
        VulnEntry {
            id: "passive-info-disclosure",
            title: "Information Disclosure in Response",
            description: "Server-side stack traces, file paths, or debug information leaked in the response body.",
            impact: "Reveals internal architecture, file paths, and technology versions to attackers.",
            remediation: "Configure error handling to return generic messages in production; disable debug mode.",
            category: "CWE-200 - Exposure of Sensitive Information",
            cwe: "CWE-200",
            references: &["https://cwe.mitre.org/data/definitions/200.html", "https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/08-Testing_for_Error_Handling/"],
        },
        VulnEntry {
            id: "passive-debug-header",
            title: "Debug Header Detected",
            description: "Debug-related HTTP headers (X-Debug-Token, X-AspNet-Version) are present in the response.",
            impact: "Reveals debug tokens or framework versions useful for targeted attacks.",
            remediation: "Remove debug headers in production deployments.",
            category: "CWE-200 - Exposure of Sensitive Information",
            cwe: "CWE-200",
            references: &["https://cwe.mitre.org/data/definitions/200.html"],
        },
        VulnEntry {
            id: "passive-jwt-exposed",
            title: "JWT Token Exposed in Response",
            description: "A JSON Web Token was found in the response body, potentially leaking authentication credentials.",
            impact: "Leaked JWTs can be used to impersonate users or escalate privileges.",
            remediation: "Never include JWTs in HTML responses; use HttpOnly cookies or secure token storage.",
            category: "API2:2023 - Broken Authentication",
            cwe: "CWE-522",
            references: &["https://portswigger.net/web-security/jwt"],
        },
        VulnEntry {
            id: "passive-jwt-none-alg",
            title: "JWT with 'none' Algorithm",
            description: "A JWT in the response uses alg:none, meaning it has no signature verification.",
            impact: "Attackers can forge arbitrary JWT tokens without a secret key.",
            remediation: "Reject JWTs with alg:none; enforce strong algorithms (RS256, ES256).",
            category: "API2:2023 - Broken Authentication",
            cwe: "CWE-345",
            references: &["https://portswigger.net/web-security/jwt/algorithm-confusion", "https://cwe.mitre.org/data/definitions/345.html"],
        },
        VulnEntry {
            id: "passive-no-ratelimit",
            title: "No Rate Limiting Headers on API",
            description: "API endpoint lacks rate-limiting headers (X-RateLimit-*, RateLimit-*, Retry-After).",
            impact: "Endpoints may be vulnerable to brute force, credential stuffing, or denial of service.",
            remediation: "Implement rate limiting and return standard rate-limit headers.",
            category: "API4:2023 - Unrestricted Resource Consumption",
            cwe: "CWE-770",
            references: &["https://owasp.org/API-Security/editions/2023/en/0xa4-unrestricted-resource-consumption/"],
        },
        VulnEntry {
            id: "passive-deser-indicator",
            title: "Serialized Object in Response",
            description: "Serialized object patterns (Java, PHP, .NET) detected in the response body.",
            impact: "If deserialized without validation, attackers may achieve remote code execution.",
            remediation: "Avoid deserializing untrusted data; use safe serialization formats like JSON.",
            category: "CWE-502 - Deserialization of Untrusted Data",
            cwe: "CWE-502",
            references: &["https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/16-Testing_for_HTTP_Incoming_Requests", "https://cwe.mitre.org/data/definitions/502.html"],
        },
        // ── Active Tests ──
        VulnEntry {
            id: "inj-sqli",
            title: "SQL Injection (SQLi)",
            description: "SQL error messages triggered by injecting a single quote, indicating unsanitized input in database queries.",
            impact: "Attackers can extract, modify, or delete database contents; may lead to full system compromise.",
            remediation: "Use parameterized queries/prepared statements; validate and sanitize all input.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-89",
            references: &["https://owasp.org/www-community/attacks/SQL_Injection", "https://cwe.mitre.org/data/definitions/89.html", "https://portswigger.net/web-security/sql-injection"],
        },
        VulnEntry {
            id: "inj-xss",
            title: "Reflected Cross-Site Scripting (XSS)",
            description: "Injected HTML/script content is reflected in the response without encoding.",
            impact: "Attackers can execute arbitrary JavaScript in victims' browsers, stealing sessions or data.",
            remediation: "Implement context-aware output encoding; deploy a strict Content-Security-Policy.",
            category: "CWE-79 - Cross-site Scripting",
            cwe: "CWE-79",
            references: &["https://owasp.org/www-community/attacks/xss/", "https://portswigger.net/web-security/cross-site-scripting", "https://cwe.mitre.org/data/definitions/79.html"],
        },
        VulnEntry {
            id: "inj-ssti",
            title: "Server-Side Template Injection (SSTI)",
            description: "Template expression was evaluated server-side, indicating user input is embedded in templates.",
            impact: "Attackers can execute arbitrary code on the server, leading to full compromise.",
            remediation: "Never embed user input directly in templates; use logic-less templates or sandboxing.",
            category: "CWE-1336 - Improper Neutralization of Special Elements Used in a Template Engine",
            cwe: "CWE-1336",
            references: &["https://portswigger.net/web-security/server-side-template-injection"],
        },
        VulnEntry {
            id: "ssrf-1",
            title: "Server-Side Request Forgery (SSRF)",
            description: "The application fetches URLs from user input and internal network references appeared in the response.",
            impact: "Attackers can access internal services, cloud metadata, and bypass firewalls.",
            remediation: "Validate and whitelist allowed URLs; block requests to internal/private IP ranges.",
            category: "API7:2023 - Server-Side Request Forgery",
            cwe: "CWE-918",
            references: &["https://owasp.org/www-community/attacks/Server_Side_Request_Forgery", "https://portswigger.net/web-security/ssrf"],
        },
        VulnEntry {
            id: "active-open-redirect",
            title: "Open Redirect",
            description: "The application redirects to a user-controlled external URL without validation.",
            impact: "Attackers can redirect users to phishing sites using a trusted domain.",
            remediation: "Validate redirect targets against an allowlist; avoid using user input in redirects.",
            category: "CWE-601 - URL Redirection to Untrusted Site",
            cwe: "CWE-601",
            references: &["https://cwe.mitre.org/data/definitions/601.html", "https://portswigger.net/kb/issues/00500100_open-redirection-reflected"],
        },
        VulnEntry {
            id: "active-path-traversal",
            title: "Path Traversal / Directory Traversal",
            description: "The application allows reading files outside the web root via ../ sequences in parameters.",
            impact: "Attackers can read sensitive system files (/etc/passwd, configuration files, source code).",
            remediation: "Validate and canonicalize file paths; use a whitelist of allowed files.",
            category: "CWE-22 - Path Traversal",
            cwe: "CWE-22",
            references: &["https://owasp.org/www-community/attacks/Path_Traversal", "https://portswigger.net/web-security/file-path-traversal"],
        },
        VulnEntry {
            id: "active-cors-reflection",
            title: "CORS Origin Reflection with Credentials",
            description: "The server reflects arbitrary Origin headers in Access-Control-Allow-Origin while allowing credentials.",
            impact: "Any website can make authenticated cross-origin requests and steal user data.",
            remediation: "Validate the Origin header against an allowlist; never reflect arbitrary origins with credentials.",
            category: "CWE-942 - Permissive Cross-domain Policy",
            cwe: "CWE-942",
            references: &["https://portswigger.net/web-security/cors", "https://portswigger.net/research/exploiting-cors-misconfigurations-for-bitcoins-and-bounties"],
        },
        VulnEntry {
            id: "active-xss-attr",
            title: "XSS via Attribute Injection",
            description: "User input is reflected inside HTML attributes without proper encoding, allowing event handler injection.",
            impact: "Attackers can execute JavaScript via crafted attribute values (onmouseover, onfocus, etc.).",
            remediation: "Apply attribute-context output encoding; use Content-Security-Policy.",
            category: "CWE-79 - Cross-site Scripting",
            cwe: "CWE-79",
            references: &["https://portswigger.net/web-security/cross-site-scripting/contexts"],
        },
        VulnEntry {
            id: "active-xss-event",
            title: "XSS via Event Handler Injection",
            description: "User input is reflected in a context where JavaScript event handlers can be injected.",
            impact: "Attackers can execute arbitrary JavaScript when users interact with the page.",
            remediation: "Encode all user input in HTML attribute contexts; implement CSP.",
            category: "CWE-79 - Cross-site Scripting",
            cwe: "CWE-79",
            references: &["https://portswigger.net/web-security/cross-site-scripting"],
        },
        VulnEntry {
            id: "active-csrf-no-token",
            title: "CSRF: Form Accepts Request Without Token",
            description: "A state-changing form accepted a POST request without a CSRF token.",
            impact: "Attackers can forge requests to perform actions on behalf of authenticated users.",
            remediation: "Require and validate CSRF tokens on all state-changing requests.",
            category: "CWE-352 - Cross-Site Request Forgery",
            cwe: "CWE-352",
            references: &["https://owasp.org/www-community/attacks/csrf", "https://portswigger.net/web-security/csrf"],
        },
        // ── Exposed Services ──
        VulnEntry {
            id: "exposed-supabase",
            title: "Exposed Supabase Database",
            description: "A Supabase REST API is publicly accessible without proper Row Level Security (RLS).",
            impact: "Attackers can read, modify, or delete database records without authentication.",
            remediation: "Enable Row Level Security (RLS) on all tables; restrict anon key permissions.",
            category: "API1:2023 - Broken Object Level Authorization",
            cwe: "CWE-284",
            references: &["https://supabase.com/docs/guides/auth/row-level-security"],
        },
        VulnEntry {
            id: "exposed-supabase-url",
            title: "Supabase URL/Key in Client Code",
            description: "Supabase project URL and API key found in client-side code.",
            impact: "While anon keys are designed to be public, misconfigured RLS can expose all data.",
            remediation: "Verify RLS policies are enabled and correctly configured on all tables.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-200",
            references: &["https://supabase.com/docs/guides/auth/row-level-security"],
        },
        VulnEntry {
            id: "exposed-firebase",
            title: "Exposed Firebase Database",
            description: "Firebase Realtime Database or Firestore is publicly readable without authentication.",
            impact: "All database contents can be read by anyone; write access may also be open.",
            remediation: "Configure Firebase Security Rules to require authentication for all operations.",
            category: "API1:2023 - Broken Object Level Authorization",
            cwe: "CWE-284",
            references: &["https://firebase.google.com/docs/rules"],
        },
        VulnEntry {
            id: "exposed-firebase-url",
            title: "Firebase Config in Client Code",
            description: "Firebase project configuration (apiKey, authDomain, databaseURL) found in client-side code.",
            impact: "While Firebase keys are designed to be public, misconfigured rules can expose all data.",
            remediation: "Verify Firebase Security Rules restrict access appropriately.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-200",
            references: &["https://firebase.google.com/docs/rules"],
        },
        VulnEntry {
            id: "exposed-pocketbase",
            title: "Exposed PocketBase Collections",
            description: "PocketBase API collections endpoint is publicly accessible, listing all data collections.",
            impact: "Attackers can enumerate and potentially access all stored data.",
            remediation: "Configure PocketBase collection rules to require authentication.",
            category: "API1:2023 - Broken Object Level Authorization",
            cwe: "CWE-284",
            references: &["https://pocketbase.io/docs/api-rules-and-filters/"],
        },
        VulnEntry {
            id: "exposed-phpmyadmin",
            title: "Exposed phpMyAdmin",
            description: "phpMyAdmin database management interface is publicly accessible.",
            impact: "Attackers can attempt to brute-force database credentials or exploit known phpMyAdmin vulnerabilities.",
            remediation: "Restrict phpMyAdmin access to trusted IPs; use strong authentication; consider removing from production.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-284",
            references: &["https://www.phpmyadmin.net/security/"],
        },
        VulnEntry {
            id: "exposed-adminer",
            title: "Exposed Adminer",
            description: "Adminer database management tool is publicly accessible.",
            impact: "Attackers can attempt database login or exploit Adminer vulnerabilities.",
            remediation: "Remove Adminer from production; restrict access to trusted IPs.",
            category: "API8:2023 - Security Misconfiguration",
            cwe: "CWE-284",
            references: &["https://www.adminer.org/en/"],
        },
        VulnEntry {
            id: "exposed-admin-panel",
            title: "Exposed Admin Panel",
            description: "An administrative interface is publicly accessible.",
            impact: "Attackers can attempt to brute-force admin credentials or exploit admin functionality.",
            remediation: "Restrict admin panel access to trusted IPs; enforce strong authentication and MFA.",
            category: "API5:2023 - Broken Function Level Authorization",
            cwe: "CWE-284",
            references: &["https://owasp.org/API-Security/editions/2023/en/0xa5-broken-function-level-authorization/"],
        },
        VulnEntry {
            id: "exposed-phpinfo",
            title: "Exposed phpinfo()",
            description: "phpinfo() output is publicly accessible, revealing full PHP configuration.",
            impact: "Reveals PHP version, extensions, environment variables, and potentially secrets.",
            remediation: "Remove phpinfo() files from production servers.",
            category: "CWE-200 - Exposure of Sensitive Information",
            cwe: "CWE-200",
            references: &["https://cwe.mitre.org/data/definitions/200.html"],
        },
        VulnEntry {
            id: "exposed-server-status",
            title: "Exposed Server Status/Info",
            description: "Apache server-status or server-info page is publicly accessible.",
            impact: "Reveals active connections, request details, and server configuration.",
            remediation: "Restrict server-status/server-info to localhost or trusted IPs.",
            category: "CWE-200 - Exposure of Sensitive Information",
            cwe: "CWE-200",
            references: &["https://httpd.apache.org/docs/2.4/mod/mod_status.html"],
        },
        VulnEntry {
            id: "exposed-debugbar",
            title: "Exposed Debug Toolbar",
            description: "A debug toolbar (Laravel Debugbar, Django Debug Toolbar, Symfony Profiler) is publicly accessible.",
            impact: "Reveals SQL queries, request data, environment variables, and application internals.",
            remediation: "Disable debug toolbars in production; set APP_DEBUG=false.",
            category: "CWE-200 - Exposure of Sensitive Information",
            cwe: "CWE-200",
            references: &["https://cwe.mitre.org/data/definitions/200.html"],
        },
        // ── CMS Checks ──
        VulnEntry {
            id: "generic-git-exposed",
            title: "Exposed .git Directory",
            description: "The .git directory is publicly accessible, potentially exposing the entire source code repository.",
            impact: "Attackers can download the full source code, including secrets, credentials, and internal logic.",
            remediation: "Block access to .git in your web server configuration.",
            category: "CWE-538 - Insertion of Sensitive Information into Externally-Accessible File",
            cwe: "CWE-538",
            references: &["https://cwe.mitre.org/data/definitions/538.html"],
        },
        VulnEntry {
            id: "generic-env-exposed",
            title: "Exposed .env File",
            description: "The .env environment file is publicly accessible, containing database credentials, API keys, and secrets.",
            impact: "Full compromise of application secrets, database access, and third-party service credentials.",
            remediation: "Block access to .env files in web server configuration; move secrets to environment variables.",
            category: "CWE-538 - Insertion of Sensitive Information into Externally-Accessible File",
            cwe: "CWE-538",
            references: &["https://cwe.mitre.org/data/definitions/538.html"],
        },
        VulnEntry {
            id: "generic-robots-sensitive",
            title: "Sensitive Paths in robots.txt",
            description: "The robots.txt file reveals paths to sensitive directories (admin, backup, config, etc.).",
            impact: "Attackers can discover hidden administrative or sensitive endpoints.",
            remediation: "Remove sensitive paths from robots.txt; use authentication instead of obscurity.",
            category: "CWE-200 - Exposure of Sensitive Information",
            cwe: "CWE-200",
            references: &["https://cwe.mitre.org/data/definitions/200.html"],
        },
        // ── BOLA / Auth Bypass ──
        VulnEntry {
            id: "bola-1",
            title: "Broken Object Level Authorization (BOLA)",
            description: "Accessing sequential object IDs returns different data, suggesting missing authorization checks.",
            impact: "Attackers can access resources belonging to other users by manipulating object IDs.",
            remediation: "Implement proper authorization checks for every object access; use UUIDs instead of sequential IDs.",
            category: "API1:2023 - Broken Object Level Authorization",
            cwe: "CWE-639",
            references: &["https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/"],
        },
    ];

    let mut map = HashMap::new();
    for entry in entries {
        map.insert(entry.id, entry);
    }
    map
});

pub fn get_vuln_info(id: &str) -> Option<&'static VulnEntry> {
    VULN_DB.get(id)
}
